language: scala
sudo: false
jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.7

env: SBT_OPTS="-Xmx4g"

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean cubicJVM/coverageTest formatJVM/coverageTest quarticJVM/coverageTest statsJVM/coverageTest toleranceJVM/coverageTest typesJVM/coverageTest utilsJVM/coverageTest
  - sbt ++$TRAVIS_SCALA_VERSION       cubicJS/coverageTest  formatJS/coverageTest  quarticJS/coverageTest  statsJS/coverageTest  toleranceJS/coverageTest  typesJS/coverageTest  utilsJS/coverageTest

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

after_success: bash <(curl -s https://codecov.io/bash)

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
